// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pojiwdiaalpfvksqgssa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvaml3ZGlhYWxwZnZrc3Fnc3NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTQxNDMsImV4cCI6MjA3MjU3MDE0M30.mdClXc3G_x_otW9-sTmk0U2Q5UkHFo7Z3jXQn4NbCBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});